name: Deploy to CloudBase

on:
  push:
    branches: [ main ]   # 推送 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install CloudBase CLI
        run: npm i -g @cloudbase/cli

      - name: Deploy to CloudBase
        env:
          TCB_SECRET_ID: ${{ secrets.TCB_SECRET_ID }}
          TCB_SECRET_KEY: ${{ secrets.TCB_SECRET_KEY }}
        run: |
          tcb login --apiKeyId $TCB_SECRET_ID --apiKey $TCB_SECRET_KEY
          tcb hosting deploy ./dist /Split-Bill -e cloud1-0g37deo4d3db8310